version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: financial-management
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      backend:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: financial-management-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:

networks:
  backend:
    driver: bridge
