server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        format_sql: true
        jdbc:
          batch_size: 1000
          fetch_size: 1000
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-management
    username: postgres
    password: postgres

  application:
    name: financial-management
  sql:
    init:
      platform: postgres
      mode: always

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

